### ISSUE TITLE
Filter (with asterix) also returns spam to inbox 

### ISSUE THREAD

**Issue by AnandSie** [la32094uf/Gmail-Inbox-Pause-Adios-Alternative#1]
The filter `*` ensures that also spam emails get's returned to my inbox.
I have not yet figured out to adjust the filter such that it does not do this.
When I have I will share this

Thank you for this project! I really like it. 
(This is my first posting on Github; I'm not sure what is expcected from me in a Issue :)

**Comment by la32094uf** [comment]
Thanks for your feedback... I’ll also have a look, would be great if we can find the correct filter. 

Another issue is that the whole thread becomes marked as unread, and that new mails sent by yourself get placed in the inbox. 

Plenty of work to do!

**Comment by AnandSie** [comment]
A small improvement could be `to:me`. This still get's all the mail but leaves emails that you have send. Email threads/conversations does still get returned because these also have emails `to:me`

**Comment by la32094uf** [comment]
Hope this resolves the problem. I will test it!

**Comment by AnandSie** [comment]
Looking around on google I found a new filter which seems to fix our two problems:
- retrieving outgoing mail
- retrieving spam 

For the second problem I first tried to extend your code by first checking if a thread [isspam()](https://developers.google.com/apps-script/reference/gmail/gmail-thread#isInSpam()). But apparently this new [filter](https://webapps.stackexchange.com/questions/119864/gmail-filter-to-match-all-incoming-messages) is enough

**Comment by la32094uf** [comment]
Great! Where did you find this? Or even better: can you try to do a pull-request with your better-filter-idea from without your Fork?

**Comment by AnandSie** [comment]
Done
